const recipes = [
  {
    id: 1,
    name: "Spaghetti Bolognese",
    country: "Italy",
    imageUrl:
      "https://images.pexels.com/photos/7218637/pexels-photo-7218637.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    ingredients: {
      pasta: "300 grams",
      groundBeef: "250 grams",
      onion: "1 whole",
      garlic: "2 cloves",
      tomatoPaste: "2 tablespoons",
      cannedTomatoes: "400 grams",
      driedOregano: "1 teaspoon",
      salt: "1 teaspoon",
      blackPepper: "1 teaspoon",
      oliveOil: "2 tablespoons",
      parmesanCheese: "1 tablespoon",
    },
  },
  {
    id: 2,
    name: "Chicken Tikka Masala",
    country: "India",
    imageUrl:
      "https://cafedelites.com/wp-content/uploads/2018/04/Best-Chicken-Tikka-Masala-IMAGE-1-1365x2048.jpg",
    ingredients: {
      chickenBreasts: "500 grams",
      yogurt: "200 grams",
      lemonJuice: "2 tablespoons",
      gingerGarlicPaste: "1 tablespoon",
      garamMasala: "2 teaspoons",
      turmericPowder: "1 teaspoon",
      paprika: "1 teaspoon",
      cuminPowder: "1 teaspoon",
      chiliPowder: "1/2 teaspoon",
      tomatoSauce: "400 grams",
      heavyCream: "200 milliliters",
      butter: "2 tablespoons",
      freshCoriander: "1 teaspoon",
      salt: "1 teaspoon",
    },
  },
  {
    id: 3,
    name: "Sushi Rolls",
    country: "Japan",
    imageUrl:
      "https://cdn.greatlifepublishing.net/wp-content/uploads/sites/2/2014/09/21140224/sushi.jpg",
    ingredients: {
      sushiRice: "2 cups",
      noriSheets: "5 whole",
      salmon: "200 grams",
      cucumber: "1 whole",
      avocado: "1 whole",
    },
  },
  {
    id: 4,
    name: "Chicken Parmesan",
    country: "Italy",
    imageUrl:
      "https://assets.bonappetit.com/photos/5ea8f0df16738800085ad5d2/4:3/w_1500,h_1125,c_limit/Chicken-Parmesean-Recipe-Lede.jpg",
    ingredients: {
      chickenBreasts: "2 whole",
      breadcrumbs: "1 cup",
      parmesanCheese: "2 cups",
      mozzarellaCheese: "2 cups",
      eggs: "2 whole",
      marinaraSauce: "1 cup",
      oliveOil: "2 tablespoons",
      freshBasil: "1 teaspoon",
      salt: "1 teaspoon",
      blackPepper: "1 teaspoon",
    },
  },
  {
    id: 5,
    name: "Pad Thai",
    country: "Thailand",
    imageUrl:
      "https://c0.wallpaperflare.com/preview/908/749/252/plant-produce-food-vegetable.jpg",
    ingredients: {
      riceNoodles: "200 grams",
      chickenBreasts: "200 grams",
      shrimp: "150 grams",
      tofu: "150 grams",
      garlic: "3 cloves",
      shallots: "2 whole",
      tamarindPaste: "3 tablespoons",
      fishSauce: "2 tablespoons",
      palmSugar: "2 tablespoons",
      eggs: "2 whole",
      peanuts: "2 cups",
      beanSprouts: "1 cup",
      lime: "2 wedges",
      redChiliFlakes: "2 tablespoons",
    },
  },
];

module.exports = recipes;
